In [94]:
import pandas as pd
import numpy as np
import os

from utils.italian_provinces import italian_provinces

In [87]:
BASE_DIR = os.getcwd()
file_path_csv = os.path.join(BASE_DIR, "Dataset", "dataset.csv")
file_path_xlsx = os.path.join(BASE_DIR, "Dataset", "StrutturaATECO-2025-IT-EN-DE.xlsx")

df_csv = pd.read_csv(file_path_csv, sep=";", encoding="latin-1")
df_xlsx = pd.read_excel(file_path_xlsx, sheet_name="ATECO 2025 Struttura")

In [88]:
df_csv.rename(columns={
    "Natura": "Nature",
    "Fatturato": "Revenue",
    "Dipendenti": "Employees",
    "Provincia": "Province"
}, inplace=True)

In [89]:
df_csv.loc[df_csv["Province"].notna(), ["City", "Region"]] = df_csv.loc[df_csv["Province"].notna(), "Province"].apply(
    lambda prov: pd.Series(italian_provinces.get(prov.strip().upper(), {"City": None, "Region": None}))
)

In [90]:
cols = list(df_csv.columns)
province_idx = cols.index("Province")
# rimuovo se esistono già
for col in ["City", "Region"]:
    if col in cols:
        cols.remove(col)
# inserisco
cols = cols[:province_idx+1] + ["City", "Region"] + cols[province_idx+1:]
df_csv = df_csv[cols]

In [91]:
# righe con Province presente ma City o Region mancanti
missing_city_region = df_csv[
    df_csv["Province"].notna() &
    (df_csv["City"].isna() | df_csv["Region"].isna())
]

print(f"Numero di righe non collegate: {len(missing_city_region)}")
missing_city_region[["Province", "City", "Region"]].head(20)  # mostra le prime 20

Numero di righe non collegate: 1886

    Province City Region
3         RM  NaN    NaN
30        RM  NaN    NaN
63        RM  NaN    NaN
75        RM  NaN    NaN
88        RM  NaN    NaN
120       TI  NaN    NaN
124       RM  NaN    NaN
139       RM  NaN    NaN
140       BT  NaN    NaN
154       RM  NaN    NaN
177       RM  NaN    NaN
201       RM  NaN    NaN
207       RM  NaN    NaN
208       FO  NaN    NaN
214       FO  NaN    NaN
240       RM  NaN    NaN
241       RM  NaN    NaN
255       RM  NaN    NaN
269       RM  NaN    NaN
277       RM  NaN    NaN

In [77]:
df_csv.head()

,ATECO,ATECO_Desc,Nature,Revenue,Employees,Province,City,Region,M-35,M-34,...,M-9,M-8,M-7,M-6,M-5,M-4,M-3,M-2,M-1,M-0
0,G.47.71.00,Commercio al dettaglio di articoli di abbiglia...,1.a Impresa,93840,2,PA,Palermo,Sicilia,80,718,...,65919,58362,69779,62338,71332,54796,91169,104473,127672,139105
1,H.49.41.00,Trasporto di merci su strada,1.a Impresa,1242280,4,MB,Monza,Lombardia,44520,43793,...,78015,73822,83936,68864,107911,37607,100365,105866,84089,95330
2,G.47.91.30,Commercio al dettaglio di qualsiasi tipo di pr...,1.a Impresa,44451177,159,MI,Milano,Lombardia,65703,87812,...,35367,41628,60515,57786,85252,76067,86415,75573,101941,237050
3,N.77.40.00,CONCESSIONE DEI DIRITTI DI SFRUTTAMENTO DI PRO...,1.a Impresa,49918687,53,RM,NaN,NaN,0,0,...,63667,74293,82637,80798,105440,74817,73151,76448,88819,85649
4,NaN,NaN,Altro / ND,0,0,NaN,NaN,NaN,240811,172007,...,47961,44201,53245,49897,81589,90283,74360,76854,62406,82700

In [78]:
df_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 20436 entries, 0 to 20435
Data columns (total 44 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ATECO       20049 non-null  str
 1   ATECO_Desc  20049 non-null  str
 2   Nature      20436 non-null  str
 3   Revenue     20436 non-null  int64
 4   Employees   20436 non-null  int64
 5   Province    16936 non-null  str
 6   City        15050 non-null  str
 7   Region      15050 non-null  str
 8   M-35        20436 non-null  int64
 9   M-34        20436 non-null  int64
 10  M-33        20436 non-null  int64
 11  M-32        20436 non-null  int64
 12  M-31        20436 non-null  int64
 13  M-30        20436 non-null  int64
 14  M-29        20436 non-null  int64
 15  M-28        20436 non-null  int64
 16  M-27        20436 non-null  int64
 17  M-26        20436 non-null  int64
 18  M-25        20436 non-null  int64
 19  M-24        20436 non-null  int64
 20  M-23        20436 non-null  int64
 21  M-22        20436 non-null  int64
 22  M-21        20436 non-null  int64
 23  M-20        20436 non-null  int64
 24  M-19        20436 non-null  int64
 25  M-18        20436 non-null  int64
 26  M-17        20436 non-null  int64
 27  M-16        20436 non-null  int64
 28  M-15        20436 non-null  int64
 29  M-14        20436 non-null  int64
 30  M-13        20436 non-null  int64
 31  M-12        20436 non-null  int64
 32  M-11        20436 non-null  int64
 33  M-10        20436 non-null  int64
 34  M-9         20436 non-null  int64
 35  M-8         20436 non-null  int64
 36  M-7         20436 non-null  int64
 37  M-6         20436 non-null  int64
 38  M-5         20436 non-null  int64
 39  M-4         20436 non-null  int64
 40  M-3         20436 non-null  int64
 41  M-2         20436 non-null  int64
 42  M-1         20436 non-null  int64
 43  M-0         20436 non-null  int64
dtypes: int64(38), str(6)
memory usage: 6.9 MB

In [79]:
df_csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 20436 entries, 0 to 20435
Data columns (total 44 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ATECO       20049 non-null  str
 1   ATECO_Desc  20049 non-null  str
 2   Nature      20436 non-null  str
 3   Revenue     20436 non-null  int64
 4   Employees   20436 non-null  int64
 5   Province    16936 non-null  str
 6   City        15050 non-null  str
 7   Region      15050 non-null  str
 8   M-35        20436 non-null  int64
 9   M-34        20436 non-null  int64
 10  M-33        20436 non-null  int64
 11  M-32        20436 non-null  int64
 12  M-31        20436 non-null  int64
 13  M-30        20436 non-null  int64
 14  M-29        20436 non-null  int64
 15  M-28        20436 non-null  int64
 16  M-27        20436 non-null  int64
 17  M-26        20436 non-null  int64
 18  M-25        20436 non-null  int64
 19  M-24        20436 non-null  int64
 20  M-23        20436 non-null  int64
 21  M-22        20436 non-null  int64
 22  M-21        20436 non-null  int64
 23  M-20        20436 non-null  int64
 24  M-19        20436 non-null  int64
 25  M-18        20436 non-null  int64
 26  M-17        20436 non-null  int64
 27  M-16        20436 non-null  int64
 28  M-15        20436 non-null  int64
 29  M-14        20436 non-null  int64
 30  M-13        20436 non-null  int64
 31  M-12        20436 non-null  int64
 32  M-11        20436 non-null  int64
 33  M-10        20436 non-null  int64
 34  M-9         20436 non-null  int64
 35  M-8         20436 non-null  int64
 36  M-7         20436 non-null  int64
 37  M-6         20436 non-null  int64
 38  M-5         20436 non-null  int64
 39  M-4         20436 non-null  int64
 40  M-3         20436 non-null  int64
 41  M-2         20436 non-null  int64
 42  M-1         20436 non-null  int64
 43  M-0         20436 non-null  int64
dtypes: int64(38), str(6)
memory usage: 6.9 MB

In [80]:
df_csv.describe()

,Revenue,Employees,M-35,M-34,M-33,M-32,M-31,M-30,M-29,M-28,...,M-9,M-8,M-7,M-6,M-5,M-4,M-3,M-2,M-1,M-0
count,2.043600e+04,20436.000000,2.043600e+04,2.043600e+04,2.043600e+04,20436.000000,20436.000000,20436.000000,20436.000000,20436.000000,...,20436.000000,20436.000000,20436.000000,20436.000000,20436.000000,20436.000000,20436.000000,20436.000000,20436.000000,20436.000000
mean,3.814559e+06,21.343120,4.844733e+02,4.754634e+02,5.199870e+02,431.743639,512.020894,424.876737,416.414954,321.661382,...,457.326140,455.670288,500.878890,449.031024,505.828929,325.216432,481.346790,547.444852,566.194510,614.266246
std,7.999604e+06,159.474594,8.178875e+03,9.540971e+03,8.653320e+03,4609.221206,8214.296953,3271.023212,3434.653672,2600.718541,...,2831.406553,2928.458317,3156.428343,2835.448864,3409.271805,2461.087865,3160.556412,3484.641725,3882.217904,4626.793992
min,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,-98444.000000,-192.000000,-163.000000,-115.000000,...,0.000000,0.000000,0.000000,-62.000000,0.000000,0.000000,0.000000,-343.000000,0.000000,0.000000
25%,0.000000e+00,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,5.217480e+05,4.000000,6.000000e+00,7.000000e+00,8.000000e+00,5.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3.275647e+06,15.000000,1.122500e+02,1.210000e+02,1.360000e+02,115.000000,117.000000,101.000000,108.000000,62.250000,...,95.000000,90.000000,104.000000,90.000000,95.000000,41.000000,87.000000,106.000000,98.000000,82.000000
max,5.792155e+07,19555.000000,1.069153e+06,1.301728e+06,1.159983e+06,508106.000000,862767.000000,218053.000000,247967.000000,178321.000000,...,80319.000000,121988.000000,134135.000000,88731.000000,144431.000000,96789.000000,139446.000000,117746.000000,198993.000000,251130.000000

In [81]:
df_csv.isnull().mean() * 100

ATECO          1.893717
ATECO_Desc     1.893717
Nature         0.000000
Revenue        0.000000
Employees      0.000000
Province      17.126639
City          26.355451
Region        26.355451
M-35           0.000000
M-34           0.000000
M-33           0.000000
M-32           0.000000
M-31           0.000000
M-30           0.000000
M-29           0.000000
M-28           0.000000
M-27           0.000000
M-26           0.000000
M-25           0.000000
M-24           0.000000
M-23           0.000000
M-22           0.000000
M-21           0.000000
M-20           0.000000
M-19           0.000000
M-18           0.000000
M-17           0.000000
M-16           0.000000
M-15           0.000000
M-14           0.000000
M-13           0.000000
M-12           0.000000
M-11           0.000000
M-10           0.000000
M-9            0.000000
M-8            0.000000
M-7            0.000000
M-6            0.000000
M-5            0.000000
M-4            0.000000
M-3            0.000000
M-2            0.000000
M-1            0.000000
M-0            0.000000
dtype: float64

In [82]:
df_xlsx.head()

,ORDINE_CODICE_ATECO_2025,CODICE_ATECO_2025,TITOLO_ITALIANO_ATECO_2025,TITOLO_INGLESE_ATECO_2025,TITOLO_TEDESCO_ATECO_2025,GERARCHIA_ATECO_2025,CODICE_PADRE_ATECO_2025,GERARCHIA_PADRE_ATECO_2025
0,1,A,"AGRICOLTURA, SILVICOLTURA E PESCA","AGRICULTURE, FORESTRY AND FISHING","LAND- UND FORSTWIRTSCHAFT, FISCHEREI",1,NaN,NaN
1,2,01,"Produzioni vegetali e animali, caccia e serviz...","Crop and animal production, hunting and relate...","Landwirtschaft, Jagd und damit verbundene Täti...",2,A,1.0
2,3,01.1,Coltivazione di colture agricole non permanenti,Growing of non-perennial crops,Anbau ein- und zweijähriger Pflanzen,3,01,2.0
3,4,01.11,"Coltivazione di cereali, legumi da granella e ...","Growing of cereals, other than rice, leguminou...",Anbau von anderem Getreide als Reis sowie von ...,4,01.1,3.0
4,5,01.11.0,"Coltivazione di cereali, legumi da granella e ...","Growing of cereals, other than rice, leguminou...",Anbau von anderem Getreide als Reis sowie von ...,5,01.11,4.0

In [83]:
df = df_csv.merge(
    df_xlsx,
    how="left",
    left_on="ATECO_2025",
    right_on="ATECO_2025"
)

KeyError: 'ATECO_2025'

In [ ]:
df.head()